---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgpadvertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - ctlplane
    - internalapi
    - storage
    - tenant
  peers: []
